# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables: 
  VmImageName: 'Windows-lates'
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }} : 
    slotTarget: 'build'
  ${{ elseif eq(variables['Build.SourceBranchName'], 'master') }} : 
    slotTarget: 'qa'   
  ${{ else }} :  
    slotTarget: 'devBuild'
    
  
jobs:
- job: buildApp 
  displayName: 'Build the Vue App' 
  #Set ENV.VARS for Webpack to read and inject during build 
  steps:  
  - task: CmdLine@2
    inputs:
      script: |
        echo Write your commands here
        echo $(slotTarget)
            
